// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/filter.ts";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Filter.tsx";
import * as $$2 from "./islands/Footer.tsx";
import * as $$3 from "./islands/Joke.tsx";

const manifest = {
  routes: {
    "./routes/api/filter.ts": $0,
    "./routes/api/joke.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Filter.tsx": $$1,
    "./islands/Footer.tsx": $$2,
    "./islands/Joke.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
